

include: "Recombination.snake"
include: "Species.snake"
include: "Global_bestrophins.snake"

rule all:
	input:
		expand("output/{domain}_recombination.svg", domain = "rhodopsins"),
		expand("species_analysis/{taxon}/treeshrink.ok", taxon = taxa.keys()),
		"output/rooted_trees.svg",
		"output/species_chronos.nwk",
		expand("output/{taxon}.svg", taxon = taxa.keys()),
		"output/bestrophins_ur50_iqtree.pdf"
		# "global_analysis/bestrophins/uniref50.fasta",
		# "global_analysis/bestrophins/uniref50.txt"
